title: "jormungandr1105@website"
tagline: "A place to log my misadventures with technology"
description: "A place to log my misadventures with technology"
github_username: jormungandr1105
baseurl: "/"
url: "https://jormungandr1105.github.io"
footer_title: "."

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-retinamagick

  
remote_theme: tareqdandachi/jekyll-shell-theme

retinamagick:
  small:
    source: assets/images
    destination: assets/images/small
    resize: "200x200"

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - read-me.md
  - projects.md
  - posts.md
  - images.md


# set the size of the text to 'large' or 'small', default is small
font-size: small
